Fix IllegalArgumentException when rotating TransferToPlayerDialogFragment
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter view
  at com.dhpcs.liquidity.fragment.TransferToPlayerDialogFragment$onCreateDialog$2.onItemSelected(TransferToPlayerDialogFragment.kt)
  at android.widget.AdapterView.fireOnSelected(AdapterView.java:931)
  at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:920)
  at android.widget.AdapterView.selectionChanged(AdapterView.java:914)
  at android.widget.AdapterView.checkSelectionChanged(AdapterView.java:1092)
  at android.widget.AdapterView.handleDataChanged(AdapterView.java:1068)
  at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:181)
  at android.widget.Spinner.onMeasure(Spinner.java:592)
  at android.support.v7.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:420)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
  at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
  at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
  at android.view.View.measure(View.java:19857)
  at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1293)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
  at android.widget.ScrollView.onMeasure(ScrollView.java:340)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
  at android.view.View.measure(View.java:19857)
  at android.support.v7.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:133)
  at android.support.v7.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:63)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
  at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
  at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
  at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
  at android.view.View.measure(View.java:19857)
  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1339)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
  at android.view.Choreographer.doCallbacks(Choreographer.java:686)
  at android.view.Choreographer.doFrame(Choreographer.java:621)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6119)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)