Fix force close when disconnecting during join (introduced by 33ecb06f0b5d)
This was the stacktrace:

java.lang.NullPointerException: Attempt to invoke virtual method 'scala.collection.immutable.Map com.dhpcs.liquidity.BoardGame$State.hiddenIdentities()' on a null object reference
	at com.dhpcs.liquidity.BoardGame.getHiddenIdentities(BoardGame.scala:445)
	at com.dhpcs.liquidity.activity.BoardGameActivity.onPrepareOptionsMenu(BoardGameActivity.java:982)
	at android.app.Activity.onPreparePanel(Activity.java:2841)
	at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:451)
	at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:440)
	at android.support.v7.internal.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:268)
	at android.support.v7.internal.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
	at android.support.v7.internal.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:555)
	at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:448)
	at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:65)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:549)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

The bug existed before 33ecb06f0b5d3e21f9b45e9615b516e2854eeb67 but didn't
manifest because the activity had always unregistered before requesting
disconnection.