Fix force close when leaving game during join to new game
This happened due to unrequestJoin being called in BoardGameActivity.onStop
while the game was in the joining state. The problem was that the join callback
wasn't checking whether a quit command was already out on the wire, so when it
determined that a new identity was required it always fed that back to
BoardGameActivity's onIdentityRequired method. Of course, though dialog
fragments can be shown when activities are stopped, in this case the stop was
followed by a change in the join state (to disconnecting), which triggers the
call to closeDialogFragments() and the resulting force close.

De-obfuscated stack trace:

java.lang.RuntimeException: Unable to stop activity {com.dhpcs.liquidity/com.dhpcs.liquidity.activity.BoardGameActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3500)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1411)
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1429)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
	at android.app.BackStackRecord.commit(BackStackRecord.java:663)
	at android.app.DialogFragment.dismissInternal(DialogFragment.java:301)
	at android.app.DialogFragment.dismiss(DialogFragment.java:267)
	at com.dhpcs.liquidity.activity.BoardGameActivity.closeDialogFragments(Unknown Source)
	at com.dhpcs.liquidity.activity.BoardGameActivity.formatCurrency(Unknown Source)
                                                   formatCurrencyValue
                                                   formatCurrencyValue
                                                   formatMemberOrAccount
                                                   playerComparator
                                                   isIdentityNameValid
                                                   onChangeGameNameError
                                                   onGameNameEntered
                                                   onIdentitiesUpdated
                                                   onIdentityCreated
                                                   onIdentityDeleteConfirmed
                                                   onIdentityNameEntered
                                                   onJoinStateChanged
                                                   onPlayerAdded
                                                   onPlayerClicked
                                                   onPlayersInitialized
                                                   onTransferAdded
                                                   onTransferValueEntered
                                                   access$000
	at com.dhpcs.liquidity.BoardGame$$anonfun$unrequestJoin$2.apply(Unknown Source)
                                                           apply
	at com.dhpcs.liquidity.BoardGame$$anonfun$unrequestJoin$2.apply(Unknown Source)
                                                           apply
	at scala.collection.immutable.Set$Set1.companion(Unknown Source)
                                        foreach
	at com.dhpcs.liquidity.BoardGame.getInstance(Unknown Source)
                                  com$dhpcs$liquidity$BoardGame$$zoneId
                                  com$dhpcs$liquidity$BoardGame$$zoneId_$eq
                                  com$dhpcs$liquidity$BoardGame$$state_$eq
                                  com$dhpcs$liquidity$BoardGame$$_joinState_$eq
                                  com$dhpcs$liquidity$BoardGame$$joinStateListeners_$eq
                                  changeGameName
                                  changeIdentityName
                                  com$dhpcs$liquidity$BoardGame$$createAccount
                                  com$dhpcs$liquidity$BoardGame$$createAndThenJoinZone
                                  deleteIdentity
                                  isIdentityNameValid
                                  isPublicKeyConnectedAndImplicitlyValid
                                  onZoneNotificationReceived
                                  onConnectionStateChanged
                                  registerListener
                                  registerListener
                                  requestJoin
                                  transferIdentity
                                  transferToPlayer
                                  unrequestJoin
                                  com$dhpcs$liquidity$BoardGame$$updateGameName
	at com.dhpcs.liquidity.activity.BoardGameActivity.onStop(Unknown Source)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1278)
	at android.app.Activity.performStop(Activity.java:6380)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3497)
	... 9 more