Fix ClassNotFoundException due to AppCompat ProGuard rule gap
Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:400)
	at java.lang.Class.forName(Class.java:326)
	at android.support.v7.app.j.b(SourceFile:1014)
	at android.support.v7.app.j.onCreateView(SourceFile:1092)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1813)
	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2554)
	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2627)
	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2047)
	at android.support.v7.app.j.x(SourceFile:374)
	at android.support.v7.app.j.w(SourceFile:323)
	at android.support.v7.app.j.b(SourceFile:284)
	at android.support.v7.app.c.setContentView(SourceFile:139)
	at com.dhpcs.liquidity.activity.GamesActivity.onCreate(SourceFile:25)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatViewInflater" on path: DexPathList[[zip file "/data/app/com.dhpcs.liquidity-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dhpcs.liquidity-1/lib/arm, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 31 more