Fix java.lang.NullPointerException regression in LastTransferFragment
Caught by pre-launch report fuzz testing:

FATAL EXCEPTION: main
Process: com.dhpcs.liquidity, PID: 11128
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacksAndMessages(java.lang.Object)' on a null object reference
	at com.dhpcs.liquidity.fragment.LastTransferFragment$onViewCreated$3.onChanged(LastTransferFragment.kt:93)
	at com.dhpcs.liquidity.fragment.LastTransferFragment$onViewCreated$3.onChanged(LastTransferFragment.kt:23)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)