Fix silent failure of ForkJoinPool
The exceptions were like this:

Failed to create ForkJoinPool for the default ExecutionContext, falling back to ThreadPoolExecutor
java.lang.Error: java.lang.NoSuchFieldException: ctl
	at scala.concurrent.forkjoin.ForkJoinPool.<clinit>(ForkJoinPool.java:3704)
	at scala.concurrent.impl.ExecutionContextImpl.createExecutorService(ExecutionContextImpl.scala:77)
	at scala.concurrent.impl.ExecutionContextImpl.<init>(ExecutionContextImpl.scala:28)
	at scala.concurrent.ExecutionContext$Implicits$.global$lzycompute(ExecutionContext.scala:130)
	at scala.concurrent.ExecutionContext$Implicits$.global(ExecutionContext.scala:130)
	at com.dhpcs.liquidity.BoardGame$$anon$5$$anonfun$onResultReceived$13.apply(BoardGame.scala:625)
	at com.dhpcs.liquidity.BoardGame$$anon$5$$anonfun$onResultReceived$13.com$dhpcs$liquidity$BoardGame$$anon$$anonfun$$$outer(BoardGame.scala:624)
                                                                       apply
	at scala.Option.isEmpty(Option.scala:158)
                 fold
	at com.dhpcs.liquidity.BoardGame$$anon$5.onResultReceived(BoardGame.scala:624)
	at com.dhpcs.liquidity.ServerConnection$$anonfun$onMessage$2$$anonfun$apply$7$$anonfun$apply$2$$anonfun$apply$mcVI$sp$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$9$$anonfun$apply$4.apply$mcV$sp(ServerConnection.scala:491)
	at com.dhpcs.liquidity.ServerConnection$$anon$1.run(ServerConnection.scala:98)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NoSuchFieldException: ctl
	at java.lang.Class.getDeclaredField(Class.java:890)
	at scala.concurrent.forkjoin.ForkJoinPool.<clinit>(ForkJoinPool.java:3683)
	... 18 more

They happened because various classes in Scala's forkjoin package use
reflection.