Fix force close regression due to 33ecb06f0b5d when rotating transfers fragment
The stacktrace was like this:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dhpcs.liquidity/com.dhpcs.liquidity.activity.BoardGameActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ArrayAdapter.clear()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
	at android.app.ActivityThread.access$900(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ArrayAdapter.clear()' on a null object reference
	at com.dhpcs.liquidity.fragment.TransferToPlayerDialogFragment.onIdentitiesUpdated(TransferToPlayerDialogFragment.java:428)
	at com.dhpcs.liquidity.activity.BoardGameActivity.onIdentitiesUpdated(BoardGameActivity.java:540)
	at com.dhpcs.liquidity.BoardGame.registerListener(BoardGame.scala:1103)
	at com.dhpcs.liquidity.activity.BoardGameActivity.onCreate(BoardGameActivity.java:454)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
	... 11 more