Fix <= Android 6.0 regression (don't use Map.getOrDefault)
This Java 8 addition is not available before Android 6.0, so prior to
this fix, releases 2.0.1 and 2.0.2 fail immediately after joining a game
with NoSuchMethodErrors.