Fix java.lang.IllegalStateException regression in command handling
Caught by pre-launch report fuzz testing:

FATAL EXCEPTION: main
Process: com.dhpcs.liquidity, PID: 9993
io.reactivex.exceptions.CompositeException: 2 exceptions occurred.
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:49)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:42)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
	at com.dhpcs.liquidity.BoardGame$createIdentity$member$1$1.accept(BoardGame.kt:643)
	at com.dhpcs.liquidity.BoardGame$createIdentity$member$1$1.accept(BoardGame.kt:19)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:138)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:38)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
  ComposedException 1 :
	kotlin.KotlinNullPointerException
		at com.dhpcs.liquidity.BoardGame$createAccount$1.subscribe(BoardGame.kt:543)
		at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
		at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
		at com.dhpcs.liquidity.BoardGame$createIdentity$member$1$1.accept(BoardGame.kt:643)
		at com.dhpcs.liquidity.BoardGame$createIdentity$member$1$1.accept(BoardGame.kt:19)
		at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
		at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
		at android.os.Handler.handleCallback(Handler.java:751)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:138)
		at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:38)
		at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
		at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
		at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
		at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
		at java.util.concurrent.FutureTask.run(FutureTask.java:237)
		at android.os.Handler.handleCallback(Handler.java:751)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at android.os.Looper.loop(Looper.java:154)
		at android.app.ActivityThread.main(ActivityThread.java:6121)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	Caused by: java.lang.IllegalStateException: Fragment CreateIdentityDialogFragment{ab4d83f} not attached to a context.
		at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
		at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
		at androidx.fragment.app.Fragment.getString(Fragment.java:795)
		at com.dhpcs.liquidity.fragment.CreateIdentityDialogFragment$onCreateDialog$alertDialog$1$2.invoke(CreateIdentityDialogFragment.kt:54)
		at com.dhpcs.liquidity.fragment.CreateIdentityDialogFragment$onCreateDialog$alertDialog$1$2.invoke(CreateIdentityDialogFragment.kt:20)
		at com.dhpcs.liquidity.activity.MainActivity$Companion$BoardGameModel$execCommand$disposable$2.accept(MainActivity.kt:139)
		at com.dhpcs.liquidity.activity.MainActivity$Companion$BoardGameModel$execCommand$disposable$2.accept(MainActivity.kt:88)
		at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
		at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
		at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
		at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
		at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
		at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
		at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:42)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
		at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
		at com.dhpcs.liquidity.BoardGame$createIdentity$member$1$1.accept(BoardGame.kt:643)
		at com.dhpcs.liquidity.BoardGame$createIdentity$member$1$1.accept(BoardGame.kt:19)
		at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
		at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
		at android.os.Handler.handleCallback(Handler.java:751)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:138)
		at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:38)
		at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
		at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
		at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
		at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
		at java.util.concurrent.FutureTask.run(FutureTask.java:237)
		at android.os.Handler.handleCallback(Handler.java:751)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at android.os.Looper.loop(Looper.java:154)
		at android.app.ActivityThread.main(ActivityThread.java:6121)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
  ComposedException 2 :
	java.lang.IllegalStateException: Fragment CreateIdentityDialogFragment{ab4d83f} not attached to a context.
		at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
		at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
		at androidx.fragment.app.Fragment.getString(Fragment.java:795)
		at com.dhpcs.liquidity.fragment.CreateIdentityDialogFragment$onCreateDialog$alertDialog$1$2.invoke(CreateIdentityDialogFragment.kt:54)
		at com.dhpcs.liquidity.fragment.CreateIdentityDialogFragment$onCreateDialog$alertDialog$1$2.invoke(CreateIdentityDialogFragment.kt:20)
		at com.dhpcs.liquidity.activity.MainActivity$Companion$BoardGameModel$execCommand$disposable$2.accept(MainActivity.kt:139)
		at com.dhpcs.liquidity.activity.MainActivity$Companion$BoardGameModel$execCommand$disposable$2.accept(MainActivity.kt:88)
		at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
		at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
		at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
		at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
		at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
		at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
		at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:42)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
		at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
		at com.dhpcs.liquidity.BoardGame$createIdentity$member$1$1.accept(BoardGame.kt:643)
		at com.dhpcs.liquidity.BoardGame$createIdentity$member$1$1.accept(BoardGame.kt:19)
		at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
		at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
		at android.os.Handler.handleCallback(Handler.java:751)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
		at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:138)
		at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:38)
		at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
		at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
		at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
		at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
		at java.util.concurrent.FutureTask.run(FutureTask.java:237)
		at android.os.Handler.handleCallback(Handler.java:751)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at android.os.Looper.loop(Looper.java:154)
		at android.app.ActivityThread.main(ActivityThread.java:6121)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)