Fix kotlin.UninitializedPropertyAccessException regression
Example:

FATAL EXCEPTION: ControllerMessenger
Process: com.dhpcs.liquidity, PID: 23041
kotlin.UninitializedPropertyAccessException: lateinit property buttonPositive has not been initialized
	at com.dhpcs.liquidity.fragment.EnterIdentityNameDialogFragment$onCreateDialog$1.invoke(EnterIdentityNameDialogFragment.kt:77)
	at com.dhpcs.liquidity.fragment.EnterIdentityNameDialogFragment$onCreateDialog$2.afterTextChanged(EnterIdentityNameDialogFragment.kt:87)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:8016)
	at android.widget.TextView.setText(TextView.java:4361)
	at android.widget.TextView.setText(TextView.java:4209)
	at android.widget.EditText.setText(EditText.java:84)
	at android.widget.TextView.setText(TextView.java:4184)
	at com.dhpcs.liquidity.fragment.EnterIdentityNameDialogFragment.onCreateDialog(EnterIdentityNameDialogFragment.kt:91)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:330)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1308)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:138)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:6)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)